# OpenTelemetry observability stack to test traces
name: 'sanitisium-observability'

services:

  app:
    build: .      
    ports:
      - '8000:8000'

  # Observability
  collector:
    image: otel/opentelemetry-collector:0.130.0@sha256:0c066d4388070dad8dc9961d9f23649e85a226620e6b359334e4a6c7f9d73b23
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - '4317:4317' # OTELP GRPC
      - '4318:4318' # OTELP HTTP

  prometheus:
    image: prom/prometheus:v3.5.0@sha256:63805ebb8d2b3920190daf1cb14a60871b16fd38bed42b857a3182bc621f4996
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-otlp-receiver
    ports:
      - '9090:9090'

  jaeger:
    image: jaegertracing/jaeger:2.8.0@sha256:af1598dfd0a7800a370e88064e24c5d562cfcbbd2c2748e6ae1f1126be88dd4b
    ports:
      - '4317' # OTELP GRPC
      - '4318' # OTELP HTTP
      - '16686:16686' # Jaeger UI
