name: Release Docker image
on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The SemVer value used by this release"
        type: string
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker-release:
    name: Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Branch sanity check
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Releases should only run from the main branch"
          exit 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: login to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        env:
          IMAGE_VERSION: ${{ github.event.inputs.semver }}
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \ 
            --tag brunojppb/sanitisium:$IMAGE_VERSION
            --push .
